# https://github.com/air-verse/air/blob/master/air_example.toml
root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
args_bin = []
bin = "./tmp/main"
cmd = "clear; go build -o ./tmp/main ./dev/main.go"
# cmd = "clear; go build -o ./tmp/main ./main.go"
exclude_dir = ["assets", "tmp", "vendor", "testdata", ".vscode"]
include_ext = ["go", "tpl", "tmpl", "html"]

[log]
main_only = true
time = false
silent = true

[misc]
clean_on_exit = false

[screen]
clear_on_rebuild = true
keep_scroll = true
